# configuration file for ideas
appname = "Ideas"
appversion = "0.0.1"
appport = "9090"
databasedir = "database/"
logdir = "logs/"
MaxSessionPerUser = 1
SessionExpireTimeInMinutes = 90
SchedularTimeIntervalInSecs = 21600
NoofBackups = 10
DataRepo = "data/"